name: Release

on:
  push:
    # branches:
    #   - main
    tags:
      - v*

jobs:
  version:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.version.outputs.version }}
    steps:
      - uses: actions/checkout@v4
      - name: Get version
        id: version
        run: |
          LATEST_TAG=v$(git describe --tags --abbrev=0 || echo "0.0.0")
          GIT_DESCRIBE=$(git describe --always --tags --long)
          # Check if the current commit is exactly on a tag
          if [[ "$GIT_DESCRIBE" == "$LATEST_TAG" ]]; then
            echo "version=${LATEST_TAG}" >> $GITHUB_OUTPUT
          else
            echo "version=${LATEST_TAG}.dev-${GIT_DESCRIBE#$LATEST_TAG-}" >> $GITHUB_OUTPUT
          fi

  pypi:
    runs-on: ubuntu-latest
    container: python:3.12
    needs: version
    steps:
      - uses: actions/checkout@v4
      - name: Install package tools
        run: pip install twine setuptools wheel
      - name: Build package
        run: python setup.py sdist bdist_wheel
      - name: Upload to PyPI
        run: twine upload dist/*
        env:
          TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}

  docker:
    runs-on: ubuntu-latest
    needs: version
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            rwnxt/pynonymizer
          tags: |
            type=raw,value=latest,enable=${{ startsWith(github.ref, 'refs/tags/v') }}
            type=raw,value=${{ needs.version.outputs.version }},enable=${{ github.event_name == 'push' }}
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}